package provider

import (
	"context"
	"time"
)

// ProviderClient is the minimal provider interface that the Runstead core depends on.
// It deliberately excludes OmniRoute-specific concepts (RouteSafety,
// GatewayContractHealth, AttemptReceipts) to keep the core portable across
// providers (OmniRoute, ChatGPT Web direct, future z.ai/Qwen).
type ProviderClient interface {
	// Complete executes one model completion request.
	// The request carries a unique ClientRequestID for deduplication and replay detection.
	// The response includes the raw model content and metadata for governor accounting.
	Complete(ctx context.Context, req ProviderRequest) (ProviderResponse, error)

	// HealthCheck validates that the provider is reachable, authenticated,
	// and the configured model is available. It must be fast (single request)
	// and is called before any task execution.
	HealthCheck(ctx context.Context) (HealthResult, error)

	// Models returns the list of models available from this provider.
	// Used for validation and discovery.
	Models(ctx context.Context) ([]ModelInfo, error)

	// Name returns a stable identifier for this provider (e.g., "omniroute", "chatgptweb").
	Name() string
}

// ProviderRequest represents one completion request from the governor to the provider.
type ProviderRequest struct {
	// ClientRequestID is a unique identifier for this request, generated by the governor.
	// It is used for deduplication and must be echoed back in ProviderResponse.Metadata.RequestID.
	ClientRequestID string

	// Model is the model identifier to use (e.g., "gpt-5.6-luna").
	Model string

	// Messages is the conversation history including system prompt and user task.
	Messages []Message

	// Stream indicates whether the provider should stream the response.
	// If true, the provider may deliver deltas via a callback (future extension).
	Stream bool
}

// Message is a single conversation message.
type Message struct {
	Role    string // "system", "user", "assistant"
	Content string
}

// ProviderResponse is the provider's completion response.
type ProviderResponse struct {
	// Content is the raw model output text. The Runstead protocol parser
	// extracts action/final envelopes from this.
	Content string

	// Metadata carries transport-level information for governor accounting,
	// observability, and replay safety.
	Metadata ProviderResponseMetadata
}

// ProviderResponseMetadata contains transport metadata from the provider response.
type ProviderResponseMetadata struct {
	// StatusCode is the HTTP status code (or equivalent) from the upstream.
	StatusCode int

	// RequestID is the upstream provider's request identifier.
	// Used for deduplication and correlation with provider logs.
	RequestID string

	// SessionID is the upstream conversation/session identifier (if applicable).
	SessionID string

	// Duration is the total time the provider spent processing the request.
	Duration time.Duration

	// RetryAfter indicates how long to wait before retrying (from Retry-After header or equivalent).
	RetryAfter time.Duration

	// ResetAt is the time when rate limits reset (from X-RateLimit-Reset or equivalent).
	ResetAt time.Time

	// Endpoint is the logical endpoint path that was called.
	Endpoint string

	// Model is the model that actually generated the response (may differ from request).
	Model string
}

// HealthResult is the result of a provider health check.
type HealthResult struct {
	// Healthy indicates whether the provider is ready to accept requests.
	Healthy bool

	// Reason explains why the provider is unhealthy (if applicable).
	// Values: "auth_expired", "model_unavailable", "endpoint_unreachable",
	// "challenge_detected", "rate_limited", "drift_detected", "configuration_error"
	Reason string

	// RateLimit contains current rate limit information if available.
	RateLimit *RateLimitInfo

	// ModelInfo contains information about the configured model if available.
	ModelInfo *ModelInfo
}

// RateLimitInfo contains rate limit details from the provider.
type RateLimitInfo struct {
	// Remaining is the number of requests remaining in the current window.
	Remaining int

	// ResetAt is when the current window resets.
	ResetAt time.Time

	// Limit is the total limit for the window (if known).
	Limit int

	// Window is the window duration (e.g., 1 hour, 1 week).
	Window time.Duration
}

// ModelInfo describes a model available from the provider.
type ModelInfo struct {
	// ID is the model identifier used in requests.
	ID string

	// DisplayName is a human-readable name.
	DisplayName string

	// ContextWindow is the maximum context size in tokens (if known).
	ContextWindow int

	// Capabilities lists special capabilities (e.g., "reasoning", "tools", "vision").
	Capabilities []string
}